name: yes
description: A package that constantly writes a string to an IOSink, simillarly to the UNIX yes utility.
version: 0.1.0
homepage: https://github.com/hacker1024/yes.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.7.2
  test: ^1.19.3
